version: 0.2

env:
  variables:
    DOCKERHUB_USERNAME: "nedumdocker"
    #DOCKERHUB_PASSWORD: "dckr_pat_cs693RxN-ofMHk_9Hn9bYYQ0tAM"  # Store the key here since System Manager is not free
    DOCKER_USERNAME: "nedumdocker"
    DOCKER_IMAGE_NAME: "seamfixapp"
    DOCKER_IMAGE_TAG: "latest"
    #DOCKERHUB_REPOSITORY: "your-dockerhub-repo/your-image"

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
     # - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 637423571998.dkr.ecr.us-east-2.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      #- docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
      - docker build -t geostore-app .

  post_build:
    commands:
      - echo "Tagging Docker image..."
      #- docker tag $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
      - docker tag geostore-app:latest 637423571998.dkr.ecr.us-east-2.amazonaws.com/geostore-app:$CODEBUILD_BUILD_NUMBER
      - echo "Pushing Docker image to Docker Hub..."
      #- docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
      - docker push 637423571998.dkr.ecr.us-east-2.amazonaws.com/geostore-app:$CODEBUILD_BUILD_NUMBER
