version: 0.2

env:
  variables:
    BUILD_NUMBER: "{CODEBUILD_BUILD_NUMBER}"

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 637423571998.dkr.ecr.us-east-2.amazonaws.com

  build:
    commands:
      - echo "Building Docker image...."
      #- docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
      - docker build -t geostore-app .

  post_build:
    commands:
      - echo "Tagging Docker image..."
      - docker tag geostore-app:latest 637423571998.dkr.ecr.us-east-2.amazonaws.com/geostore-app:$BUILD_NUMBER
      - echo "Pushing Docker image to Docker Hub..."
      - docker push 637423571998.dkr.ecr.us-east-2.amazonaws.com/geostore-app:$BUILD_NUMBER
      - echo $BUILD_NUMBER > build_number.txt

artifacts:
  files:
    - appspec.yml
    - script/deploy.sh
    - build_number.txt
