version: 0.2

env:
  variables:
    DOCKERHUB_USERNAME: "nedumdocker"
    DOCKERHUB_PASSWORD: "dckr_pat_blDfhsWzUJq-A0FAz4mjqYbszRw"  #(System Manager is not Free thus I will store the key here instead of using KVM)
    DOCKER_USERNAME: "nedumdocker"
    DOCKER_IMAGE_NAME: "seamfix-app"
    DOCKER_IMAGE_TAG: "latest"
    #DOCKERHUB_REPOSITORY: "your-dockerhub-repo/your-image"

  #parameter-store:                     
   # DOCKERHUB_USERNAME: "/dockerhub/username"
    #DOCKERHUB_PASSWORD: "/dockerhub/password"

phases:

  pre_build:
    commands:
      echo "Logging in to Docker Hub..."
      echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

  build:
    commands:
      echo "Building Docker image..."
      docker build -t $DOCKER_USERNAME/DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

  post_build:
    commands:
      echo "Tagging Docker image..."
      
      echo "Pushing Docker image to Docker Hub..."
      docker push $DOCKER_USERNAME/DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
